### ISSUE TITLE
add Amap lib?

### ISSUE THREAD

**Issue by sonygod** [cx20/gltf-test#186]
https://lbs.amap.com/api/javascript-api/example/mesh/3d-gltf

will you add this lib for test?

**Comment by cx20** [comment]
Thank you for introducing me to this interesting library.
I am currently testing this library in my local environment.
I'm considering whether or not to add it to the gltf-test repository.
Because of the recent growth of the library, I may move it to another repository, such as gis-gltf-test.

BTW, is there an open place where I can ask questions about this library?
I would like to report a problem when the glTF file cannot be read properly.

**Comment by sonygod** [comment]
You can report to here , may be you need an account at first.

https://console.amap.com/dev/ticket/type/webService

only 中文 support.
