### ISSUE TITLE
add UnityGLTF to  test  list? 

### ISSUE THREAD

**Issue by sonygod** [cx20/gltf-test#63]
https://github.com/KhronosGroup/UnityGLTF

how about add UnityGLTF to test lists?

**Comment by cx20** [comment]
> how about add UnityGLTF to test lists?

I'm not familiar with Unity, so it's difficult to prepare the sample code myself.
However, I would like to merge with `gltf-test` if you can prepare and `PR` an executable sample like other WebGL libraries.

Or, another proposal may be to prepare a test different from WebGL.
For example, the idea is to individually test applications that support glTF, such as Paint 3D and Office.
In that case, it may be better to divide it into another repository because the concept is different. For example, `gltf-app-test`.

**Comment by sonygod** [comment]
unity can public webgl target. I'll check your code  and try to build the sample code in unity.

then PR.
